[window]
opacity = 0.9
dimensions = { columns = 120, lines = 30 }
decorations = "Buttonless"
padding = { x = 10, y = 5 }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 17

[cursor]
style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = true

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" }
]
